 
services:
  fastapi:
    build: 
        context: .
        dockerfile: build/Dockerfile
    ports:
      - 8000:8000
    env_file: "build/.env"
    runtime: nvidia
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "./:/app/api/"
    