name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Runs on the latest Ubuntu runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 # Check out the code in the repository

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Uses the GitHub username for authentication
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Set up Buildx for advanced build features

      - name: Set repository name to lowercase
        id: repo_name
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
